### ISSUE TITLE
Crop Using Coordinates

### ISSUE THREAD

**Issue by keremkusmezer** [MasayukiSuda/GPUVideo-android#1]
Hi,

Thanks for the wonderfull library and it is great to see you merged all the other libraries you developed into one single library.

Is it possible to apply crop on the video using x , y coordinates and width and height?

Regards
Kerem Küsmezer

**Comment by MasayukiSuda** [comment]
see this.
https://github.com/MasayukiSuda/Mp4Composer-android/issues/36#issuecomment-515538130
