### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [MasayukiSuda/GPUVideo-android#13]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by MasayukiSuda** [comment]
That sounds great. Would love to set a logo that goes with the concept!

**Comment by mansya** [comment]
HI, sir, I have designed it. How ? do you like it ? if yes please tell me which one you like.
![GPUVideo](https://user-images.githubusercontent.com/33461607/59967406-85230600-9553-11e9-9f7f-54de77d54e99.png)

**Comment by mansya** [comment]
hi sir. how about this offer. don't you want to continue?

**Comment by MasayukiSuda** [comment]
sorry, I like center. blue logo.

**Comment by mansya** [comment]
hi sir. I have sent you [**Pull Requests.**](https://github.com/MasayukiSuda/GPUVideo-android/pull/20) please check. and I have also uploaded all files to this [**Drive.**](https://drive.google.com/open?id=1soJFH844s6S_ibEW3TteNgnwuLEwfmXq)

**Comment by MasayukiSuda** [comment]
Thanks!!
