### ISSUE TITLE
The app is crashing on the release build with androidx

### ISSUE THREAD

**Issue by HirenBharodiya** [MasayukiSuda/GPUVideo-android#25]
java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.video.VideoListener.onSurfaceSizeChanged(int, int)"
        at com.google.android.exoplayer2.SimpleExoPlayer.maybeNotifySurfaceSizeChanged(SimpleExoPlayer.java:1172)
        at com.google.android.exoplayer2.SimpleExoPlayer.setVideoSurface(SimpleExoPlayer.java:321)
        at com.daasuu.gpuv.player.GPUPlayerRenderer.onSurfaceCreated(GPUPlayerRenderer.java:94)
        at com.daasuu.gpuv.egl.GlFrameBufferObjectRenderer.onSurfaceCreated(GlFrameBufferObjectRenderer.java:38)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1551)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1279)

**Comment by alxgord** [comment]
Faced same issue

**Comment by alxgord** [comment]
Issue happened because GPUPlayerView dont implement onSurfaceSizeChanged(int width, int height) method of VideoListener

**Comment by trexsiddharth** [comment]
Did u guys solved it?

**Comment by kerimovscreations** [comment]
Can you provide your xml structure of gpuplayer layout with parent layout? @trexsiddharth

**Comment by trexsiddharth** [comment]
@kerimovscreations  here it is

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:id="@+id/rlPreview"
    tools:context="com.blessme.app.Video_Recording.Preview_Video_A">
    

<com.blessme.app.Video_Recording.MovieWrapperView
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:resize_mode="fixed_height"
    android:id="@+id/layout_movie_wrapper"/>

    <ImageButton
        android:layout_width="40dp"
        android:layout_height="40dp"
        android:layout_marginTop="35dp"
        android:layout_marginLeft="10dp"
        android:scaleType="fitCenter"
        android:padding="3dp"
        android:id="@+id/Goback"
        android:src="@drawable/ic_back"
        android:background="@color/transparent"/>

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Next"
        android:textSize="15dp"
        android:textStyle="bold"
        android:paddingTop="10dp"
        android:paddingBottom="10dp"
        android:paddingRight="20dp"
        android:paddingLeft="20dp"
        android:layout_marginBottom="15dp"
        android:layout_marginRight="10dp"
        android:id="@+id/next_btn"
        android:layout_above="@+id/recylerview"
        android:textColor="@color/white"
        android:background="@color/redcolor"
        android:layout_alignParentRight="true"/>

    <androidx.recyclerview.widget.RecyclerView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/recylerview"
        android:paddingBottom="20dp"
        android:background="@color/fifty_transparent_black"
        android:layout_alignParentBottom="true"/>


</RelativeLayout>

**Comment by trexsiddharth** [comment]
@kerimovscreations  here it is

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:id="@+id/rlPreview"
    tools:context="com.blessme.app.Video_Recording.Preview_Video_A">


<com.blessme.app.Video_Recording.MovieWrapperView
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:resize_mode="fixed_height"
    android:id="@+id/layout_movie_wrapper"/>

    <ImageButton
        android:layout_width="40dp"
        android:layout_height="40dp"
        android:layout_marginTop="35dp"
        android:layout_marginLeft="10dp"
        android:scaleType="fitCenter"
        android:padding="3dp"
        android:id="@+id/Goback"
        android:src="@drawable/ic_back"
        android:background="@color/transparent"/>

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Next"
        android:textSize="15dp"
        android:textStyle="bold"
        android:paddingTop="10dp"
        android:paddingBottom="10dp"
        android:paddingRight="20dp"
        android:paddingLeft="20dp"
        android:layout_marginBottom="15dp"
        android:layout_marginRight="10dp"
        android:id="@+id/next_btn"
        android:layout_above="@+id/recylerview"
        android:textColor="@color/white"
        android:background="@color/redcolor"
        android:layout_alignParentRight="true"/>

    <androidx.recyclerview.widget.RecyclerView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/recylerview"
        android:paddingBottom="20dp"
        android:background="@color/fifty_transparent_black"
        android:layout_alignParentBottom="true"/>


</RelativeLayout>

**Comment by trexsiddharth** [comment]
@kerimovscreations  here it is 

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:id="@+id/rlPreview"
    tools:context="com.blessme.app.Video_Recording.Preview_Video_A">

<com.blessme.app.Video_Recording.MovieWrapperView
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:resize_mode="fixed_height"
    android:id="@+id/layout_movie_wrapper"/>

    <ImageButton
        android:layout_width="40dp"
        android:layout_height="40dp"
        android:layout_marginTop="35dp"
        android:layout_marginLeft="10dp"
        android:scaleType="fitCenter"
        android:padding="3dp"
        android:id="@+id/Goback"
        android:src="@drawable/ic_back"
        android:background="@color/transparent"/>

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Next"
        android:textSize="15dp"
        android:textStyle="bold"
        android:paddingTop="10dp"
        android:paddingBottom="10dp"
        android:paddingRight="20dp"
        android:paddingLeft="20dp"
        android:layout_marginBottom="15dp"
        android:layout_marginRight="10dp"
        android:id="@+id/next_btn"
        android:layout_above="@+id/recylerview"
        android:textColor="@color/white"
        android:background="@color/redcolor"
        android:layout_alignParentRight="true"/>

    <androidx.recyclerview.widget.RecyclerView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/recylerview"
        android:paddingBottom="20dp"
        android:background="@color/fifty_transparent_black"
        android:layout_alignParentBottom="true"/>
</RelativeLayout>

**Comment by trexsiddharth** [comment]
these are inside a relative layout

**Comment by torindev** [comment]
any updates?

**Comment by torindev** [comment]
[Similar problem](https://github.com/eneim/toro/issues/445) (this solved my problem)

> @bakhytk Add the following line to your `gradle.properties` file:
> 
> `android.enableDexingArtifactTransform=false`
> 
> The problem resides in a new feature of the gradle build tools 3.5 where it tries to optimize external dependencies as well and it strips default method implementations from exoplayer.
> According to the android team issue tracker this issue should be fixed by correctly declaring all dependencies and transient dependencies on the `pom.xml` but I couldn't find any solution other than this.

**Comment by Umesh-Kumar19** [comment]
Same Issue:

java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.video.VideoListener.onSurfaceSizeChanged(int, int)"
        at com.google.android.exoplayer2.SimpleExoPlayer.maybeNotifySurfaceSizeChanged(SimpleExoPlayer.java:1504)
        at com.google.android.exoplayer2.SimpleExoPlayer.setVideoSurface(SimpleExoPlayer.java:542)
        at com.daasuu.gpuv.player.GPUPlayerRenderer.onSurfaceCreated(GPUPlayerRenderer.java:94)
        at com.daasuu.gpuv.egl.GlFrameBufferObjectRenderer.onSurfaceCreated(GlFrameBufferObjectRenderer.java:38)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1543)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1271)

Have you find any solution for new versions of gradle and androidX? Issue occurred only in signed apk file.

**Comment by HirenBharodiya** [comment]
> Same Issue:
> 
> java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.video.VideoListener.onSurfaceSizeChanged(int, int)"
> at com.google.android.exoplayer2.SimpleExoPlayer.maybeNotifySurfaceSizeChanged(SimpleExoPlayer.java:1504)
> at com.google.android.exoplayer2.SimpleExoPlayer.setVideoSurface(SimpleExoPlayer.java:542)
> at com.daasuu.gpuv.player.GPUPlayerRenderer.onSurfaceCreated(GPUPlayerRenderer.java:94)
> at com.daasuu.gpuv.egl.GlFrameBufferObjectRenderer.onSurfaceCreated(GlFrameBufferObjectRenderer.java:38)
> at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1543)
> at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1271)
> 
> Have you find any solution for new versions of gradle and androidX? Issue occurred only in signed apk file.

Try this https://github.com/MasayukiSuda/GPUVideo-android/issues/25#issuecomment-601202923

**Comment by darktheft** [comment]
Same Issue

java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.video.VideoListener.onSurfaceSizeChanged(int, int)"
at com.google.android.exoplayer2.SimpleExoPlayer.maybeNotifySurfaceSizeChanged(SimpleExoPlayer.java:1504)
at com.google.android.exoplayer2.SimpleExoPlayer.setVideoSurface(SimpleExoPlayer.java:542)
at com.daasuu.gpuv.player.GPUPlayerRenderer.onSurfaceCreated(GPUPlayerRenderer.java:94)
at com.daasuu.gpuv.egl.GlFrameBufferObjectRenderer.onSurfaceCreated(GlFrameBufferObjectRenderer.java:38)
at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1543)
at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1271)

Have you found any solution for new versions of Gradle and androids? An issue occurred only in the signed apk file.

*********DEVICE INFORMATION***********
Brand: xiaomi
Device: lavender
Model: Redmi Note 7s
************FIRMWARE******************
SDK: 29
Release: 10

**Comment by shirosoft** [comment]
Add the following line to your gradle.properties file:

android.enableDexingArtifactTransform=false

Credits to dear torindev
