### ISSUE TITLE
GLSurfaceView - it's view, it has nothing to do with adding filters on video during recording (final video file, e.g. mp4)

### ISSUE THREAD

**Issue by anonym24** [MasayukiSuda/GPUVideo-android#36]
![image](https://user-images.githubusercontent.com/8851301/74587099-0e151300-4ff7-11ea-9b8b-380165b83015.png)

**Comment by anonym24** [comment]
![image](https://user-images.githubusercontent.com/8851301/74587099-0e151300-4ff7-11ea-9b8b-380165b83015.png)

**Comment by anonym24** [comment]
e.g. using Camera2 API I can record video in background, and I don't add any views, it has nothing to do with UI. So how I can use this library in this case?

**Comment by MasayukiSuda** [comment]
There is no such pattern.
