### ISSUE TITLE
Video content length is zero

### ISSUE THREAD

**Issue by jianinz** [MasayukiSuda/GPUVideo-android#46]
Integrate GPUVideo-android with our app, the video file was successfully generated with reasonable size, although when opening it via VLC or QuickTime Player, the duration/content length says 00:00.

Any ideas?

Library Version: 0.1.1
Phone: Google Pixel 2

**Comment by jianinz** [comment]
Figure it out, nothing to do with library, closing it

**Comment by iamkdblue** [comment]
Yes same with me, why recording time showing 0.
