### ISSUE TITLE
preview issue

### ISSUE THREAD

**Issue by shyamprmr** [MasayukiSuda/GPUVideo-android#5]
when i set filter than try  to record video preview not showing on full screen

**Comment by MasayukiSuda** [comment]
I do not know exactly what you are talking about.

**Comment by shyamprmr** [comment]
[image: pic.png]
[image: pic1.png]

*tested on   Samsung galaxy s5*
when i record  video without applying filter preview show on full screen
but when i apply filter and try to record preview it shows on half screen
shown in above pic.





*Shyam Parmar*

*Android Developer*
*Mob. No. - +917067144471,+919171212185*
*Mega Mind Tracker Consultancy Softech Pvt. Ltd.*

*Software Development | Website Designing | App Development*
*INDORE*
http://www.mmtcshub.com <http://../>
Email: mmtcs.shyamparmar*@gmail.com <mmtcs.shyamparmar@gmail.com>*
215-217 Bakhatgarh Tower,opposite to apna sweets ,near zanzeerwala square
Indore

**Comment by MasayukiSuda** [comment]
show image and tell me how record?
Camera ? Mp4Composer ?

**Comment by shyamprmr** [comment]
Please watch this video from below link, testing device galaxy s5, android
version -6 (marshmallow)

https://drive.google.com/open?id=0B5EGnQiCejFnaDloeXJIRnB5aTRqRFctX0JHZEZtczNHWEM4
*Shyam Parmar*

*Android Developer*
*Mob. No. - +917067144471,+919171212185*
*Mega Mind Tracker Consultancy Softech Pvt. Ltd.*

*Software Development | Website Designing | App Development*
*INDORE*
http://www.mmtcshub.com <http://../>
Email: mmtcs.shyamparmar*@gmail.com <mmtcs.shyamparmar@gmail.com>*
215-217 Bakhatgarh Tower,opposite to apna sweets ,near zanzeerwala square
Indore
