### ISSUE TITLE
Bitmap overlay filter is filickering in Camera Preview while recording

### ISSUE THREAD

**Issue by patolax** [MasayukiSuda/GPUVideo-android#68]
Reproduce Steps

1. Go to Camera Record 
1. Select portrait
1. Select Bitmap overlay filter at the very bottom

1. Record the vid

The flickering starts to happen in a few seconds and keep on going throughout the recording. However, that effect is not recorded in the recorded video file. That is its just a preview related artifact which will really spook the user.

**Comment by jianinz** [comment]
Hey @patolax are you still experiencing the flickering or is it solved arealdy?

**Comment by patolax** [comment]
I was able to get rid of it. It looks fine now. But I have a bigger issue. 

The time difference between each onFrameAvailable call is around 150-200 milliseconds. So that when I try to draw some animation on SurfaceTexture, FPS is super low. Is there a way to improve this time lag.

**Comment by jianinz** [comment]
are you drawing the animation in the preview renderer?

btw: how did you solve the flickering issue? would you mind sharing it?

**Comment by patolax** [comment]
I am drawing it using Gloverlayfilter class. preview renderer calls that filter. The issues is that time between onFrameAvailable call is super big so animation is slow. 

I think it went away when I stopped subclassing Gloverlayfilter. That is I did not use bimapfiler or watermarkfilter.
